### ISSUE TITLE
This public instance has been down for a long time: `rsshub.woodland.cafe`

### ISSUE THREAD

**Issue by AiraNadih** [RSSNext/rsshub-docs#93]
It seems that regardless of which route is accessed, it always returns a 429 error code.

**Comment by AiraNadih** [comment]
I'd be happy to provide more details:

- The instance consistently returns HTTP 429 errors
- This behavior has been observed across all routes
- This has been ongoing for several months
- I've tested using different browsers and times of day with the same result

Please let me know if any additional information is needed to help investigate this issue.

**Comment by TonyRL** [comment]
@untitaker Could you have a look at your instance?

**Comment by untitaker** [comment]
My instance isn't down, I use it myself. Yes, I have rate-limits. Please send the IP you used and/or user-agent to admin AT woodland DOT cafe.

**Comment by AiraNadih** [comment]
> My instance isn't down, I use it myself. Yes, I have rate-limits. Please send the IP you used and/or user-agent to admin AT woodland DOT cafe.

However, this means anyone wanting to use your instance needs to send you their IP or user-agent first.

Can this still be called a `public instance`?

**Comment by untitaker** [comment]
In principle you don't need to send me your IP first. that's just to debug why you're constantly hitting rate limits. there's no whitelist or anything, I'd just look into access logs to see what happened.

I'll admit that the rate limits I have are very restrictive, but that's just because there's a few scrapers out there that really cause load problems. If this impacts legitimate use I can tweak them. but again, I need something to search logs by.

**Comment by AiraNadih** [comment]
@untitaker Actually, I haven't used any aggressive requesting rates.

I was simply testing all public RSSHub instances in a normal way, but found that your instance mysteriously triggers 429 errors every time.

That's why I questioned whether this instance can still be called a `public instance`.

To help you check the logs, I just accessed the `/bbc/world-asia` route again through the proxy node that triggers the 429 error.

**Comment by untitaker** [comment]
I raised the limits just now. Please let me know if this is ok for your usage. Assuming you use a normal RSS reader, I would not pay too much attention to initial 429. many RSS readers try to hammer the feed every 10 minutes and adjust over time as the server rejects their requests.

**Comment by AiraNadih** [comment]
> I raised the limits just now. Please let me know if this is ok for your usage. Assuming you use a normal RSS reader, I would not pay too much attention to initial 429. many RSS readers try to hammer the feed every 10 minutes and adjust over time as the server rejects their requests.

The instance appears to be working normally now, without the unexplained 429 errors that were occurring previously. Thank you for adjusting the rate limits.

I'm using Miniflux, so the current configuration should work fine for my use case.
